import { FontFamily, Color, FontSize } from "@digi-wallet/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  debitTypo: {
    textAlign: "left",
    fontFamily: FontFamily.mulishBold,
    fontWeight: "700",
    position: "absolute",
  },
  logoFlexBox: {
    textAlign: "right",
    color: Color.colorSnow,
    position: "absolute",
  },
  mastercardLayout: {
    bottom: "23.86%",
    width: "61.58%",
    height: "76.14%",
    maxHeight: "100%",
    overflow: "hidden",
    maxWidth: "100%",
    top: "0%",
    position: "absolute",
  },
  textTypo: {
    fontFamily: FontFamily.mulishSemiBold,
    fontWeight: "600",
    textAlign: "left",
    color: Color.colorSnow,
    position: "absolute",
  },
  card6Child: {
    height: "100%",
    width: "100%",
    bottom: "0%",
    borderRadius: 6,
    borderStyle: "solid",
    borderColor: Color.colorGray,
    borderWidth: 0.3,
    backgroundColor: "transparent",
    left: "0%",
    right: "0%",
    top: "0%",
    position: "absolute",
  },
  card6Item: {
    height: "10.99%",
    width: "8.96%",
    top: "32.51%",
    right: "83.58%",
    bottom: "56.5%",
    maxHeight: "100%",
    overflow: "hidden",
    maxWidth: "100%",
    left: "7.46%",
    position: "absolute",
  },
  ciromaChineyeAdekunle: {
    top: "88.02%",
    color: Color.colorSnow,
    textAlign: "left",
    fontSize: FontSize.size_xs,
    left: "7.46%",
  },
  bankName: {
    left: "67.14%",
    fontSize: FontSize.size_base,
    fontWeight: "800",
    fontFamily: FontFamily.mulishExtraBold,
    top: "5.99%",
  },
  debit: {
    top: "5.99%",
    color: Color.colorSnow,
    textAlign: "left",
    fontSize: FontSize.size_xs,
    left: "7.46%",
  },
  logo: {
    height: "5.99%",
    width: "9.97%",
    top: "13.43%",
    left: "81.71%",
    fontSize: FontSize.size_xs_1,
    display: "none",
    fontFamily: FontFamily.mulishBold,
    fontWeight: "700",
    textAlign: "right",
  },
  mastercardChild: {
    left: "38.42%",
    right: "0%",
  },
  mastercardItem: {
    right: "38.42%",
    left: "0%",
  },
  mastercard1: {
    height: "23.86%",
    width: "84.01%",
    top: "76.14%",
    left: "10.29%",
    fontSize: FontSize.size_4xs_4,
    color: Color.colorWhite,
  },
  mastercard: {
    height: "18.82%",
    width: "14.55%",
    top: "75.19%",
    right: "7.46%",
    bottom: "5.99%",
    left: "77.99%",
    position: "absolute",
  },
  validThru: {
    left: "7.73%",
    fontSize: FontSize.size_7xs,
    top: "70.27%",
    fontWeight: "600",
  },
  text: {
    left: "14.68%",
    top: "70.27%",
    fontWeight: "600",
    fontSize: FontSize.size_xs,
  },
  text1: {
    top: "47.05%",
    left: "7.75%",
    fontSize: FontSize.size_5xl,
    letterSpacing: 1.2,
  },
  card6: {
    width: 374,
    height: 234,
  },
});
